apiVersion: apps/v1
kind: Deployment
metadata:
  name: aerogest-backend
  labels:
    app: aerogest-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aerogest-backend
  template:
    metadata:
      labels:
        app: aerogest-backend
    spec:
      containers:
      - name: backend
        image: seu-registro/aerogest-backend:latest
        ports:
        - containerPort: 3001
        envFrom:
        - secretRef:
            name: aerogest-secrets
        readinessProbe:
          httpGet:
            path: /
            port: 3001
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 3001
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: aerogest-backend
spec:
  selector:
    app: aerogest-backend
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: ClusterIP
