apiVersion: apps/v1
kind: Deployment
metadata:
  name: aerogest-frontend
  labels:
    app: aerogest-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aerogest-frontend
  template:
    metadata:
      labels:
        app: aerogest-frontend
    spec:
      containers:
      - name: frontend
        image: seu-registro/aerogest-frontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: NEXT_PUBLIC_API_URL
          value: "http://aerogest-backend:3001"
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: aerogest-frontend
spec:
  selector:
    app: aerogest-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
