apiVersion: apps/v1
kind: Deployment
metadata:
  name: aerogest-mongo
  labels:
    app: aerogest-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aerogest-mongo
  template:
    metadata:
      labels:
        app: aerogest-mongo
    spec:
      containers:
      - name: mongo
        image: mongo:6.0
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
      volumes:
      - name: mongo-data
        persistentVolumeClaim:
          claimName: mongo-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: aerogest-mongo
spec:
  selector:
    app: aerogest-mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
