name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: \${{ secrets.DOCKER_USERNAME }}
        password: \${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push backend image
      run: |
        docker build -t yourdockerhubusername/aerogest-backend:latest ./AeroGest/sistema-unificado/backend
        docker push yourdockerhubusername/aerogest-backend:latest

    - name: Build and push frontend image
      run: |
        docker build -t yourdockerhubusername/aerogest-frontend:latest ./AeroGest/sistema-gerenciamento-voos-frontend
        docker push yourdockerhubusername/aerogest-frontend:latest

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Configure kubeconfig
      run: |
        echo "\${{ secrets.KUBE_CONFIG }}" > kubeconfig.yaml
        export KUBECONFIG=$(pwd)/kubeconfig.yaml

    - name: Deploy backend to Kubernetes
      run: |
        kubectl apply -f k8s/backend-deployment.yaml

    - name: Deploy frontend to Kubernetes
      run: |
        kubectl apply -f k8s/frontend-deployment.yaml

    - name: Deploy MongoDB to Kubernetes
      run: |
        kubectl apply -f k8s/mongo-deployment.yaml

    - name: Deploy Secrets to Kubernetes
      run: |
        kubectl apply -f k8s/secrets.yaml
